### PR TITLE
Feature/font size tweaks

### PR DESCRIPTION
**Pull request by rockacola**
* Font size tweaking to better fit design while retaining as much accessibility as feasible.
* Fix minor English spelling mistake (commit https://github.com/neo-ngd/neo.org/commit/2dc44f03327abe703a49d9a33d66f1f3d0ebac31)

### CODE REVIEW

**Comment by steven1227** [comment]
For this PR, I need @liuqiang1357 to test on multi size devices.

**Comment by liuqiang1357** [comment]
Sorry, I don’t understand why we don’t use rem directly, but use less variables named xxx-px. What’s the point of doing this?

**Comment by rockacola** [comment]
> Sorry, I don’t understand why we don’t use rem directly, but use less variables named xxx-px. What’s the point of doing this?

Programmatically, it doesn't make any difference but to provide visual assistance.

The design talks (and will continue to talk) in pixel, having an alias means we are better at making design changes and troubleshoot. It's also less prompt to mistakes.

It'll be ideal to have a mixin to do the calculation during transpile time (example: `px_to_rem("32")`) but for now, the provided approach has no technical barrier.

**Comment by liuqiang1357** [comment]
> > Sorry, I don’t understand why we don’t use rem directly, but use less variables named xxx-px. What’s the point of doing this?
> 
> Programmatically, it doesn't make any difference but to provide visual assistance.
> 
> The design talks (and will continue to talk) in pixel, having an alias means we are better at making design changes and troubleshoot. It's also less prompt to mistakes.
> 
> It'll be ideal to have a mixin to do the calculation during transpile time (example: `px_to_rem("32")`) but for now, the provided approach has no technical barrier.

That's reasonable, but you can use some design tools to directly see the rem size, such as [Lanhu](https://lanhuapp.com/). And if this approach is partially introduced, it may cause some inconsistencies, which I think is not conducive to subsequent maintenance.

**Comment by rockacola** [comment]
> That's reasonable, but you can use some design tools to directly see the rem size, such as Lanhu. And if this approach is partially introduced, it may cause some inconsistencies, which I think is not conducive to subsequent maintenance.

Thanks for the feedback.

I don't see how this is causes inconsistencies to the design though, because instead of `font-size: 0.875rem;`, it is using alias `font-size: @font-size-14px;`, which is exactly the same after you run through the transpiler.

There will be multiple scenarios where you will have different font sizes at each defined breakpoints, using alias will make the code way more readable:

```css
.block-paragraph {
    font-size: @font-size-16px;
    @media (min-width: 768px) {
        font-size: @font-size-14px;
    }
    @media (min-width: 1024px) {
        font-size: @font-size-13px;
    }
    @media (min-width: 1440px) {
        font-size: @font-size-18px;
    }
}
```

Please consider :pray:

**Comment by liuqiang1357** [comment]
> Thanks for the feedback.
> 
> I don't see how this is causes inconsistencies to the design though, because instead of `font-size: 0.875rem;`, it is using alias `font-size: @font-size-14px;`, which is exactly the same after you run through the transpiler.
> 
> There will be multiple scenarios where you will have different font sizes at each defined breakpoints, using alias will make the code way more readable:
> 
> ```css
> .block-paragraph {
>     font-size: @font-size-16px;
>     @media (min-width: 768px) {
>         font-size: @font-size-14px;
>     }
>     @media (min-width: 1024px) {
>         font-size: @font-size-13px;
>     }
>     @media (min-width: 1440px) {
>         font-size: @font-size-18px;
>     }
> }
> ```
> 
> Please consider 🙏

Okay, I will merge this PR, but before that, can you please update the sitecn.less file as well, this is the global css file for the Chinese page.

**Review by steven1227 — APPROVED** [review]

**Comment by rockacola** [comment]
I provided minor tweaks to `sitecn.less`:

* Remove redefinition of global base font size
* For style customization due to i18n, I encourage to utilize `html[lang="LANG_CODE"]` at component level.

I'm not aware there are any design guidelines when it comes to Chinese i18n, is there @liuqiang1357 ?
If not, going forward I will propose further intuitive refinement in future PRs.

**Comment by liuqiang1357** [comment]
PR merged. Thanks for your excellent work!

**Pull request merged**
